-- Zimlo — seed data generated from src/data/menuData.js
-- Run this in the Supabase SQL Editor AFTER schema.sql.
insert into dishes (id, subcategory, name, name_hi, price, veg, img) values
('ff1', 'fast-food', 'Veg Burger', 'वेज बर्गर', 79, true, '🍔'),
('ff2', 'fast-food', 'Cheese Sandwich', 'चीज़ सैंडविच', 69, true, '🥪'),
('ff3', 'fast-food', 'French Fries', 'फ्रेंच फ्राइज़', 89, true, '🍟'),
('ff4', 'fast-food', 'Chicken Burger', 'चिकन बर्गर', 109, false, '🍔'),
('ff5', 'fast-food', 'Veg Cheese Burst Burger', 'वेज चीज़ बर्स्ट बर्गर', 99, true, '🍔'),
('ff6', 'fast-food', 'Peri Peri Fries', 'पेरी पेरी फ्राइज़', 99, true, '🍟'),
('ff7', 'fast-food', 'Chicken Nuggets (6 pc)', 'चिकन नगेट्स (6 पीस)', 129, false, '🍗'),
('ff8', 'fast-food', 'Grilled Sandwich', 'ग्रिल्ड सैंडविच', 79, true, '🥪'),
('ff9', 'fast-food', 'Corn Cheese Nuggets', 'कॉर्न चीज़ नगेट्स', 89, true, '🧀'),
('ff10', 'fast-food', 'Chicken Popcorn', 'चिकन पॉपकॉर्न', 119, false, '🍗'),
('ff11', 'fast-food', 'Aloo Tikki Burger', 'आलू टिक्की बर्गर', 59, true, '🍔'),
('ff12', 'fast-food', 'Veg Hot Dog', 'वेज हॉट डॉग', 89, true, '🌭'),
('ff13', 'fast-food', 'Club Sandwich', 'क्लब सैंडविच', 99, true, '🥪'),
('ff14', 'fast-food', 'Cheese Corn Balls (6 pc)', 'चीज़ कॉर्न बॉल्स (6 पीस)', 109, true, '🧀'),
('ff15', 'fast-food', 'Chicken Wings (6 pc)', 'चिकन विंग्स (6 पीस)', 149, false, '🍗'),
('ff16', 'fast-food', 'Veg Momos (8 pc)', 'वेज मोमोज़ (8 पीस)', 79, true, '🥟'),
('ff17', 'fast-food', 'Chicken Momos (8 pc)', 'चिकन मोमोज़ (8 पीस)', 109, false, '🥟'),
('ni1', 'north-indian', 'Paneer Butter Masala', 'पनीर बटर मसाला', 149, true, '🍛'),
('ni2', 'north-indian', 'Dal Makhani', 'दाल मखनी', 119, true, '🍲'),
('ni3', 'north-indian', 'Butter Chicken', 'बटर चिकन', 189, false, '🍗'),
('ni4', 'north-indian', 'Tandoori Roti (2 pc)', 'तंदूरी रोटी (2 पीस)', 30, true, '🫓'),
('ni5', 'north-indian', 'Kadai Paneer', 'कड़ाही पनीर', 159, true, '🍛'),
('ni6', 'north-indian', 'Chole Bhature', 'छोले भटूरे', 99, true, '🍛'),
('ni7', 'north-indian', 'Rajma Chawal', 'राजमा चावल', 109, true, '🍚'),
('ni8', 'north-indian', 'Chicken Curry', 'चिकन करी', 179, false, '🍛'),
('ni9', 'north-indian', 'Mutton Curry', 'मटन करी', 249, false, '🍛'),
('ni10', 'north-indian', 'Palak Paneer', 'पालक पनीर', 139, true, '🍲'),
('ni11', 'north-indian', 'Shahi Paneer', 'शाही पनीर', 159, true, '🍛'),
('ni12', 'north-indian', 'Dal Tadka', 'दाल तड़का', 99, true, '🍲'),
('ni13', 'north-indian', 'Jeera Rice', 'जीरा राइस', 89, true, '🍚'),
('ni14', 'north-indian', 'Butter Naan (2 pc)', 'बटर नान (2 पीस)', 50, true, '🫓'),
('ni15', 'north-indian', 'Tandoori Chicken (Half)', 'तंदूरी चिकन (हाफ)', 199, false, '🍗'),
('ni16', 'north-indian', 'Malai Kofta', 'मलाई कोफ्ता', 149, true, '🍛'),
('ni17', 'north-indian', 'Mix Veg', 'मिक्स वेज', 119, true, '🍛'),
('ni18', 'north-indian', 'Egg Curry', 'एग करी', 109, false, '🍛'),
('si1', 'south-indian', 'Masala Dosa', 'मसाला डोसा', 89, true, '🥞'),
('si2', 'south-indian', 'Idli Sambhar (4 pc)', 'इडली सांभर (4 पीस)', 69, true, '🍚'),
('si3', 'south-indian', 'Medu Vada (2 pc)', 'मेदू वड़ा (2 पीस)', 59, true, '🍩'),
('si4', 'south-indian', 'Plain Dosa', 'प्लेन डोसा', 69, true, '🥞'),
('si5', 'south-indian', 'Onion Rava Dosa', 'प्याज़ रवा डोसा', 99, true, '🥞'),
('si6', 'south-indian', 'Uttapam', 'उत्तपम', 89, true, '🥞'),
('si7', 'south-indian', 'Rava Idli (4 pc)', 'रवा इडली (4 पीस)', 79, true, '🍚'),
('si8', 'south-indian', 'Curd Rice', 'दही चावल', 79, true, '🍚'),
('si9', 'south-indian', 'Lemon Rice', 'नींबू चावल', 79, true, '🍚'),
('si10', 'south-indian', 'Mysore Masala Dosa', 'मैसूर मसाला डोसा', 99, true, '🥞'),
('si11', 'south-indian', 'Sambhar Vada (2 pc)', 'सांभर वड़ा (2 पीस)', 69, true, '🍩'),
('si12', 'south-indian', 'Filter Coffee', 'फिल्टर कॉफी', 39, true, '☕'),
('ch1', 'chinese', 'Veg Noodles', 'वेज नूडल्स', 99, true, '🍜'),
('ch2', 'chinese', 'Veg Manchurian', 'वेज मंचूरियन', 109, true, '🥘'),
('ch3', 'chinese', 'Chicken Fried Rice', 'चिकन फ्राइड राइस', 139, false, '🍛'),
('ch4', 'chinese', 'Veg Fried Rice', 'वेज फ्राइड राइस', 99, true, '🍛'),
('ch5', 'chinese', 'Chicken Noodles', 'चिकन नूडल्स', 129, false, '🍜'),
('ch6', 'chinese', 'Chilli Paneer', 'चिल्ली पनीर', 139, true, '🥘'),
('ch7', 'chinese', 'Chilli Chicken', 'चिल्ली चिकन', 159, false, '🍗'),
('ch8', 'chinese', 'Schezwan Noodles', 'सेज़वान नूडल्स', 119, true, '🍜'),
('ch9', 'chinese', 'Spring Rolls (4 pc)', 'स्प्रिंग रोल्स (4 पीस)', 99, true, '🥢'),
('ch10', 'chinese', 'Manchow Soup', 'मंचाउ सूप', 79, true, '🥣'),
('ch11', 'chinese', 'Hot & Sour Soup', 'हॉट एंड सोर सूप', 79, true, '🥣'),
('ch12', 'chinese', 'Chicken Manchurian', 'चिकन मंचूरियन', 149, false, '🥘'),
('ch13', 'chinese', 'American Chopsuey', 'अमेरिकन चॉपसुई', 129, true, '🍜'),
('bk1', 'bakery-items', 'Chocolate Pastry', 'चॉकलेट पेस्ट्री', 59, true, '🍰'),
('bk2', 'bakery-items', 'Bread Pack', 'ब्रेड पैक', 45, true, '🍞'),
('bk3', 'bakery-items', 'Cookies (200g)', 'कुकीज़ (200g)', 79, true, '🍪'),
('bk4', 'bakery-items', 'Black Forest Slice', 'ब्लैक फॉरेस्ट स्लाइस', 69, true, '🍰'),
('bk5', 'bakery-items', 'Red Velvet Cupcake', 'रेड वेलवेट कपकेक', 55, true, '🧁'),
('bk6', 'bakery-items', 'Veg Puff', 'वेज पफ', 25, true, '🥐'),
('bk7', 'bakery-items', 'Bun Butter', 'बन बटर', 30, true, '🍞'),
('bk8', 'bakery-items', 'Donut', 'डोनट', 45, true, '🍩'),
('bk9', 'bakery-items', 'Croissant', 'क्रॉइसां', 65, true, '🥐'),
('bk10', 'bakery-items', 'Brownie', 'ब्राउनी', 59, true, '🍫'),
('bv1', 'beverages', 'Masala Chai', 'मसाला चाय', 20, true, '☕'),
('bv2', 'beverages', 'Cold Coffee', 'कोल्ड कॉफी', 69, true, '🥤'),
('bv3', 'beverages', 'Fresh Lime Soda', 'फ्रेश लाइम सोडा', 49, true, '🥤'),
('bv4', 'beverages', 'Mango Lassi', 'मैंगो लस्सी', 59, true, '🥤'),
('bv5', 'beverages', 'Sweet Lassi', 'मीठी लस्सी', 49, true, '🥤'),
('bv6', 'beverages', 'Oreo Shake', 'ओरियो शेक', 89, true, '🥤'),
('bv7', 'beverages', 'Chocolate Shake', 'चॉकलेट शेक', 89, true, '🥤'),
('bv8', 'beverages', 'Fresh Orange Juice', 'फ्रेश ऑरेंज जूस', 69, true, '🧃'),
('bv9', 'beverages', 'Buttermilk (Chaas)', 'छाछ', 25, true, '🥛'),
('bv10', 'beverages', 'Iced Tea', 'आइस्ड टी', 59, true, '🧋'),
('pz1', 'pizza', 'Margherita Pizza (Regular)', 'मार्गेरिटा पिज़्ज़ा (रेगुलर)', 129, true, '🍕'),
('pz2', 'pizza', 'Farmhouse Pizza (Regular)', 'फार्महाउस पिज़्ज़ा (रेगुलर)', 179, true, '🍕'),
('pz3', 'pizza', 'Paneer Tikka Pizza (Regular)', 'पनीर टिक्का पिज़्ज़ा (रेगुलर)', 199, true, '🍕'),
('pz4', 'pizza', 'Chicken Tikka Pizza (Regular)', 'चिकन टिक्का पिज़्ज़ा (रेगुलर)', 229, false, '🍕'),
('pz5', 'pizza', 'Cheese Burst Pizza (Regular)', 'चीज़ बर्स्ट पिज़्ज़ा (रेगुलर)', 219, true, '🍕'),
('pz6', 'pizza', 'Pepperoni Pizza (Regular)', 'पेपेरोनी पिज़्ज़ा (रेगुलर)', 239, false, '🍕'),
('pz7', 'pizza', 'Garlic Bread (4 pc)', 'गार्लिक ब्रेड (4 पीस)', 89, true, '🍞'),
('rw1', 'rolls-wraps', 'Veg Roll', 'वेज रोल', 59, true, '🌯'),
('rw2', 'rolls-wraps', 'Paneer Roll', 'पनीर रोल', 79, true, '🌯'),
('rw3', 'rolls-wraps', 'Chicken Roll', 'चिकन रोल', 99, false, '🌯'),
('rw4', 'rolls-wraps', 'Egg Roll', 'एग रोल', 69, false, '🌯'),
('rw5', 'rolls-wraps', 'Mutton Seekh Roll', 'मटन सीक रोल', 129, false, '🌯'),
('rw6', 'rolls-wraps', 'Double Egg Chicken Roll', 'डबल एग चिकन रोल', 119, false, '🌯'),
('rw7', 'rolls-wraps', 'Schezwan Paneer Wrap', 'सेज़वान पनीर रैप', 89, true, '🌯'),
('th1', 'thali', 'Veg Thali', 'वेज थाली', 149, true, '🍱'),
('th2', 'thali', 'Deluxe Veg Thali', 'डीलक्स वेज थाली', 199, true, '🍱'),
('th3', 'thali', 'Non-Veg Thali', 'नॉन-वेज थाली', 229, false, '🍱'),
('th4', 'thali', 'South Indian Combo', 'साउथ इंडियन कॉम्बो', 139, true, '🍱'),
('th5', 'thali', 'Burger + Fries Combo', 'बर्गर + फ्राइज़ कॉम्बो', 149, true, '🍱'),
('th6', 'thali', 'Chinese Combo (Noodles + Manchurian)', 'चाइनीज़ कॉम्बो (नूडल्स + मंचूरियन)', 179, true, '🍱'),
('sf1', 'street-food', 'Pani Puri (6 pc)', 'पानी पूरी (6 पीस)', 39, true, '🥟'),
('sf2', 'street-food', 'Bhel Puri', 'भेल पूरी', 49, true, '🥗'),
('sf3', 'street-food', 'Samosa (2 pc)', 'समोसा (2 पीस)', 30, true, '🥟'),
('sf4', 'street-food', 'Vada Pav (2 pc)', 'वड़ा पाव (2 पीस)', 40, true, '🍔'),
('sf5', 'street-food', 'Pav Bhaji', 'पाव भाजी', 89, true, '🍛'),
('sf6', 'street-food', 'Dahi Puri', 'दही पूरी', 49, true, '🥗'),
('sf7', 'street-food', 'Aloo Chaat', 'आलू चाट', 49, true, '🥗'),
('sf8', 'street-food', 'Kachori (2 pc)', 'कचौड़ी (2 पीस)', 35, true, '🥟'),
('sf9', 'street-food', 'Sev Puri', 'सेव पूरी', 49, true, '🥗'),
('ds1', 'desserts', 'Gulab Jamun (4 pc)', 'गुलाब जामुन (4 पीस)', 59, true, '🍡'),
('ds2', 'desserts', 'Rasgulla (4 pc)', 'रसगुल्ला (4 पीस)', 59, true, '🍡'),
('ds3', 'desserts', 'Ice Cream Cup', 'आइसक्रीम कप', 49, true, '🍨'),
('ds4', 'desserts', 'Kaju Katli (250g)', 'काजू कतली (250g)', 199, true, '🍬'),
('ds5', 'desserts', 'Jalebi (250g)', 'जलेबी (250g)', 79, true, '🍥'),
('ds6', 'desserts', 'Rasmalai (2 pc)', 'रसमलाई (2 पीस)', 69, true, '🍡'),
('ds7', 'desserts', 'Gajar Halwa', 'गाजर हलवा', 79, true, '🍮'),
('ds8', 'desserts', 'Chocolate Brownie with Ice Cream', 'चॉकलेट ब्राउनी विद आइसक्रीम', 99, true, '🍫')
on conflict (id) do nothing;
